import { Injectable, isDevMode } from '@angular/core';
import { of } from 'rxjs';
import { map } from 'rxjs/operators';
import { BreakpointService } from '../../../layout/breakpoint/breakpoint.service';
import { TableConfig } from './config/table.config';
import * as i0 from "@angular/core";
import * as i1 from "../../../layout/breakpoint/breakpoint.service";
import * as i2 from "./config/table.config";
/**
 * Responsive table service.
 *
 * The `TableService` is used to generate a `TableStructure` based on configuration. The table
 * structure configuration allows for breakpoint specific configuration, so that the table
 * experience can be differentiated various screen sizes.
 *
 * The table structure configuration is driven by a table type. The various supported
 * table types are exposed in feature libraries.
 *
 * If there is no table configuration for the given type found, a table header structure
 * is generated based on the actual data or randomly (in case no data is passed in) by
 * generating 5 headers. In case of a generated header, we warn the developer in devMode that
 * there is no configuration available.
 */
export class TableService {
    constructor(breakpointService, config) {
        this.breakpointService = breakpointService;
        this.config = config;
    }
    /**
     * Builds the table structure. The table structure can be created by the help of
     * the `tableType`. The `tableType` can be used in the configuration `TableConfig`,
     * so that the table headers can be defined.
     */
    buildStructure(tableType, data$) {
        if (this.hasTableConfig(tableType)) {
            return this.buildStructureFromConfig(tableType);
        }
        else {
            if (data$) {
                return this.buildStructureFromData(tableType, data$);
            }
            else {
                return this.buildRandomStructure(tableType);
            }
        }
    }
    /**
     * Returns the table structure by configuration. The configuration can be
     * breakpoint-driven, which means that an alternative header structure can
     * be created per screen size.
     *
     * The breakpoint is resolved by teh `BreakpointService`.
     */
    buildStructureFromConfig(type) {
        return this.breakpointService.breakpoint$.pipe(map((breakpoint) => (Object.assign(Object.assign({}, this.getTableConfig(type, breakpoint)), { type }))));
    }
    /**
     * This method generates a table structure by the help of the first data row.
     */
    buildStructureFromData(type, data$) {
        this.warn(`No table configuration found to render table with type "${type}". The table header for "${type}" is generated by the help of the first data item`);
        return data$.pipe(map((data) => {
            const headers = Object.keys(data === null || data === void 0 ? void 0 : data[0]).map((key) => ({
                key,
                label: key,
            }));
            return {
                type: type,
                headers,
            };
        }));
    }
    /**
     * As a last resort, the table structure is randomly created. We add 5 unknown headers
     * and use the `hideHeader` to avoid the unknown headers to be rendered.
     */
    buildRandomStructure(type) {
        this.warn(`No data available for "${type}", a random structure is generated (with hidden table headers).`);
        return of({
            type,
            headers: [
                { key: 'unknown' },
                { key: 'unknown' },
                { key: 'unknown' },
                { key: 'unknown' },
                { key: 'unknown' },
            ],
            hideHeader: true,
        });
    }
    /**
     * Finds the best applicable table configuration for the given type
     * and breakpoint. If there is no configuration available for the breakpoint,
     * the best match will be returned, using mobile first approach.
     *
     * If there is no match for any breakpoint, the fallback is a configuration
     * without the notion of a breakpoint. Otherwise we fallback to the first
     * available config.
     */
    getTableConfig(type, breakpoint) {
        const tableConfig = this.config.table[type];
        // find all relevant breakpoints
        const current = this.breakpointService.breakpoints.indexOf(breakpoint);
        const relevant = this.breakpointService.breakpoints
            .slice(0, current + 1)
            .reverse();
        const bestMatch = relevant.find((br) => !!tableConfig.find((structure) => structure.breakpoint === br));
        return bestMatch
            ? tableConfig.find((config) => config.breakpoint === bestMatch)
            : tableConfig.find((structure) => !structure.breakpoint) ||
                tableConfig[0];
    }
    hasTableConfig(tableType) {
        var _a;
        return !!((_a = this.config.table) === null || _a === void 0 ? void 0 : _a[tableType]);
    }
    /**
     * Prints a convenient message in the console to increase developer experience.
     */
    warn(message) {
        if (isDevMode) {
            console.warn(message);
        }
    }
}
TableService.ɵprov = i0.ɵɵdefineInjectable({ factory: function TableService_Factory() { return new TableService(i0.ɵɵinject(i1.BreakpointService), i0.ɵɵinject(i2.TableConfig)); }, token: TableService, providedIn: "root" });
TableService.decorators = [
    { type: Injectable, args: [{
                providedIn: 'root',
            },] }
];
TableService.ctorParameters = () => [
    { type: BreakpointService },
    { type: TableConfig }
];
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidGFibGUuc2VydmljZS5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIi4uLy4uLy4uLy4uLy4uLy4uL3Byb2plY3RzL3N0b3JlZnJvbnRsaWIvc3JjL3NoYXJlZC9jb21wb25lbnRzL3RhYmxlL3RhYmxlLnNlcnZpY2UudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUEsT0FBTyxFQUFFLFVBQVUsRUFBRSxTQUFTLEVBQUUsTUFBTSxlQUFlLENBQUM7QUFFdEQsT0FBTyxFQUFjLEVBQUUsRUFBRSxNQUFNLE1BQU0sQ0FBQztBQUN0QyxPQUFPLEVBQUUsR0FBRyxFQUFFLE1BQU0sZ0JBQWdCLENBQUM7QUFDckMsT0FBTyxFQUFFLGlCQUFpQixFQUFFLE1BQU0sK0NBQStDLENBQUM7QUFDbEYsT0FBTyxFQUFFLFdBQVcsRUFBRSxNQUFNLHVCQUF1QixDQUFDOzs7O0FBR3BEOzs7Ozs7Ozs7Ozs7OztHQWNHO0FBSUgsTUFBTSxPQUFPLFlBQVk7SUFDdkIsWUFDWSxpQkFBb0MsRUFDcEMsTUFBbUI7UUFEbkIsc0JBQWlCLEdBQWpCLGlCQUFpQixDQUFtQjtRQUNwQyxXQUFNLEdBQU4sTUFBTSxDQUFhO0lBQzVCLENBQUM7SUFFSjs7OztPQUlHO0lBQ0gsY0FBYyxDQUNaLFNBQWlCLEVBQ2pCLEtBQXVCO1FBRXZCLElBQUksSUFBSSxDQUFDLGNBQWMsQ0FBQyxTQUFTLENBQUMsRUFBRTtZQUNsQyxPQUFPLElBQUksQ0FBQyx3QkFBd0IsQ0FBQyxTQUFTLENBQUMsQ0FBQztTQUNqRDthQUFNO1lBQ0wsSUFBSSxLQUFLLEVBQUU7Z0JBQ1QsT0FBTyxJQUFJLENBQUMsc0JBQXNCLENBQUMsU0FBUyxFQUFFLEtBQUssQ0FBQyxDQUFDO2FBQ3REO2lCQUFNO2dCQUNMLE9BQU8sSUFBSSxDQUFDLG9CQUFvQixDQUFDLFNBQVMsQ0FBQyxDQUFDO2FBQzdDO1NBQ0Y7SUFDSCxDQUFDO0lBRUQ7Ozs7OztPQU1HO0lBQ08sd0JBQXdCLENBQUMsSUFBWTtRQUM3QyxPQUFPLElBQUksQ0FBQyxpQkFBaUIsQ0FBQyxXQUFXLENBQUMsSUFBSSxDQUM1QyxHQUFHLENBQUMsQ0FBQyxVQUFVLEVBQUUsRUFBRSxDQUFDLGlDQUFNLElBQUksQ0FBQyxjQUFjLENBQUMsSUFBSSxFQUFFLFVBQVUsQ0FBQyxLQUFFLElBQUksSUFBRyxDQUFDLENBQzFFLENBQUM7SUFDSixDQUFDO0lBRUQ7O09BRUc7SUFDTyxzQkFBc0IsQ0FDOUIsSUFBWSxFQUNaLEtBQXNCO1FBRXRCLElBQUksQ0FBQyxJQUFJLENBQ1AsMkRBQTJELElBQUksNEJBQTRCLElBQUksbURBQW1ELENBQ25KLENBQUM7UUFDRixPQUFPLEtBQUssQ0FBQyxJQUFJLENBQ2YsR0FBRyxDQUFDLENBQUMsSUFBVyxFQUFFLEVBQUU7WUFDbEIsTUFBTSxPQUFPLEdBQUcsTUFBTSxDQUFDLElBQUksQ0FBQyxJQUFJLGFBQUosSUFBSSx1QkFBSixJQUFJLENBQUcsQ0FBQyxFQUFFLENBQUMsR0FBRyxDQUFDLENBQUMsR0FBRyxFQUFFLEVBQUUsQ0FBQyxDQUFDO2dCQUNuRCxHQUFHO2dCQUNILEtBQUssRUFBRSxHQUFHO2FBQ1gsQ0FBQyxDQUFDLENBQUM7WUFDSixPQUFPO2dCQUNMLElBQUksRUFBRSxJQUFJO2dCQUNWLE9BQU87YUFDVSxDQUFDO1FBQ3RCLENBQUMsQ0FBQyxDQUNILENBQUM7SUFDSixDQUFDO0lBRUQ7OztPQUdHO0lBQ08sb0JBQW9CLENBQUMsSUFBWTtRQUN6QyxJQUFJLENBQUMsSUFBSSxDQUNQLDBCQUEwQixJQUFJLGlFQUFpRSxDQUNoRyxDQUFDO1FBRUYsT0FBTyxFQUFFLENBQUM7WUFDUixJQUFJO1lBQ0osT0FBTyxFQUFFO2dCQUNQLEVBQUUsR0FBRyxFQUFFLFNBQVMsRUFBRTtnQkFDbEIsRUFBRSxHQUFHLEVBQUUsU0FBUyxFQUFFO2dCQUNsQixFQUFFLEdBQUcsRUFBRSxTQUFTLEVBQUU7Z0JBQ2xCLEVBQUUsR0FBRyxFQUFFLFNBQVMsRUFBRTtnQkFDbEIsRUFBRSxHQUFHLEVBQUUsU0FBUyxFQUFFO2FBQ25CO1lBQ0QsVUFBVSxFQUFFLElBQUk7U0FDakIsQ0FBQyxDQUFDO0lBQ0wsQ0FBQztJQUVEOzs7Ozs7OztPQVFHO0lBQ08sY0FBYyxDQUN0QixJQUFZLEVBQ1osVUFBc0I7UUFFdEIsTUFBTSxXQUFXLEdBQUcsSUFBSSxDQUFDLE1BQU0sQ0FBQyxLQUFLLENBQUMsSUFBSSxDQUFDLENBQUM7UUFFNUMsZ0NBQWdDO1FBQ2hDLE1BQU0sT0FBTyxHQUFHLElBQUksQ0FBQyxpQkFBaUIsQ0FBQyxXQUFXLENBQUMsT0FBTyxDQUFDLFVBQVUsQ0FBQyxDQUFDO1FBQ3ZFLE1BQU0sUUFBUSxHQUFHLElBQUksQ0FBQyxpQkFBaUIsQ0FBQyxXQUFXO2FBQ2hELEtBQUssQ0FBQyxDQUFDLEVBQUUsT0FBTyxHQUFHLENBQUMsQ0FBQzthQUNyQixPQUFPLEVBQUUsQ0FBQztRQUViLE1BQU0sU0FBUyxHQUFlLFFBQVEsQ0FBQyxJQUFJLENBQ3pDLENBQUMsRUFBRSxFQUFFLEVBQUUsQ0FBQyxDQUFDLENBQUMsV0FBVyxDQUFDLElBQUksQ0FBQyxDQUFDLFNBQVMsRUFBRSxFQUFFLENBQUMsU0FBUyxDQUFDLFVBQVUsS0FBSyxFQUFFLENBQUMsQ0FDdkUsQ0FBQztRQUVGLE9BQU8sU0FBUztZQUNkLENBQUMsQ0FBQyxXQUFXLENBQUMsSUFBSSxDQUFDLENBQUMsTUFBTSxFQUFFLEVBQUUsQ0FBQyxNQUFNLENBQUMsVUFBVSxLQUFLLFNBQVMsQ0FBQztZQUMvRCxDQUFDLENBQUMsV0FBVyxDQUFDLElBQUksQ0FBQyxDQUFDLFNBQVMsRUFBRSxFQUFFLENBQUMsQ0FBQyxTQUFTLENBQUMsVUFBVSxDQUFDO2dCQUNwRCxXQUFXLENBQUMsQ0FBQyxDQUFDLENBQUM7SUFDdkIsQ0FBQztJQUVTLGNBQWMsQ0FBQyxTQUFpQjs7UUFDeEMsT0FBTyxDQUFDLFFBQUMsSUFBSSxDQUFDLE1BQU0sQ0FBQyxLQUFLLDBDQUFHLFNBQVMsRUFBQyxDQUFDO0lBQzFDLENBQUM7SUFFRDs7T0FFRztJQUNLLElBQUksQ0FBQyxPQUFPO1FBQ2xCLElBQUksU0FBUyxFQUFFO1lBQ2IsT0FBTyxDQUFDLElBQUksQ0FBQyxPQUFPLENBQUMsQ0FBQztTQUN2QjtJQUNILENBQUM7Ozs7WUFsSUYsVUFBVSxTQUFDO2dCQUNWLFVBQVUsRUFBRSxNQUFNO2FBQ25COzs7WUFyQlEsaUJBQWlCO1lBQ2pCLFdBQVciLCJzb3VyY2VzQ29udGVudCI6WyJpbXBvcnQgeyBJbmplY3RhYmxlLCBpc0Rldk1vZGUgfSBmcm9tICdAYW5ndWxhci9jb3JlJztcbmltcG9ydCB7IEJSRUFLUE9JTlQgfSBmcm9tICcuLi8uLi8uLi9sYXlvdXQvY29uZmlnL2xheW91dC1jb25maWcnO1xuaW1wb3J0IHsgT2JzZXJ2YWJsZSwgb2YgfSBmcm9tICdyeGpzJztcbmltcG9ydCB7IG1hcCB9IGZyb20gJ3J4anMvb3BlcmF0b3JzJztcbmltcG9ydCB7IEJyZWFrcG9pbnRTZXJ2aWNlIH0gZnJvbSAnLi4vLi4vLi4vbGF5b3V0L2JyZWFrcG9pbnQvYnJlYWtwb2ludC5zZXJ2aWNlJztcbmltcG9ydCB7IFRhYmxlQ29uZmlnIH0gZnJvbSAnLi9jb25maWcvdGFibGUuY29uZmlnJztcbmltcG9ydCB7IFRhYmxlU3RydWN0dXJlLCBUYWJsZVN0cnVjdHVyZUNvbmZpZ3VyYXRpb24gfSBmcm9tICcuL3RhYmxlLm1vZGVsJztcblxuLyoqXG4gKiBSZXNwb25zaXZlIHRhYmxlIHNlcnZpY2UuXG4gKlxuICogVGhlIGBUYWJsZVNlcnZpY2VgIGlzIHVzZWQgdG8gZ2VuZXJhdGUgYSBgVGFibGVTdHJ1Y3R1cmVgIGJhc2VkIG9uIGNvbmZpZ3VyYXRpb24uIFRoZSB0YWJsZVxuICogc3RydWN0dXJlIGNvbmZpZ3VyYXRpb24gYWxsb3dzIGZvciBicmVha3BvaW50IHNwZWNpZmljIGNvbmZpZ3VyYXRpb24sIHNvIHRoYXQgdGhlIHRhYmxlXG4gKiBleHBlcmllbmNlIGNhbiBiZSBkaWZmZXJlbnRpYXRlZCB2YXJpb3VzIHNjcmVlbiBzaXplcy5cbiAqXG4gKiBUaGUgdGFibGUgc3RydWN0dXJlIGNvbmZpZ3VyYXRpb24gaXMgZHJpdmVuIGJ5IGEgdGFibGUgdHlwZS4gVGhlIHZhcmlvdXMgc3VwcG9ydGVkXG4gKiB0YWJsZSB0eXBlcyBhcmUgZXhwb3NlZCBpbiBmZWF0dXJlIGxpYnJhcmllcy5cbiAqXG4gKiBJZiB0aGVyZSBpcyBubyB0YWJsZSBjb25maWd1cmF0aW9uIGZvciB0aGUgZ2l2ZW4gdHlwZSBmb3VuZCwgYSB0YWJsZSBoZWFkZXIgc3RydWN0dXJlXG4gKiBpcyBnZW5lcmF0ZWQgYmFzZWQgb24gdGhlIGFjdHVhbCBkYXRhIG9yIHJhbmRvbWx5IChpbiBjYXNlIG5vIGRhdGEgaXMgcGFzc2VkIGluKSBieVxuICogZ2VuZXJhdGluZyA1IGhlYWRlcnMuIEluIGNhc2Ugb2YgYSBnZW5lcmF0ZWQgaGVhZGVyLCB3ZSB3YXJuIHRoZSBkZXZlbG9wZXIgaW4gZGV2TW9kZSB0aGF0XG4gKiB0aGVyZSBpcyBubyBjb25maWd1cmF0aW9uIGF2YWlsYWJsZS5cbiAqL1xuQEluamVjdGFibGUoe1xuICBwcm92aWRlZEluOiAncm9vdCcsXG59KVxuZXhwb3J0IGNsYXNzIFRhYmxlU2VydmljZSB7XG4gIGNvbnN0cnVjdG9yKFxuICAgIHByb3RlY3RlZCBicmVha3BvaW50U2VydmljZTogQnJlYWtwb2ludFNlcnZpY2UsXG4gICAgcHJvdGVjdGVkIGNvbmZpZzogVGFibGVDb25maWdcbiAgKSB7fVxuXG4gIC8qKlxuICAgKiBCdWlsZHMgdGhlIHRhYmxlIHN0cnVjdHVyZS4gVGhlIHRhYmxlIHN0cnVjdHVyZSBjYW4gYmUgY3JlYXRlZCBieSB0aGUgaGVscCBvZlxuICAgKiB0aGUgYHRhYmxlVHlwZWAuIFRoZSBgdGFibGVUeXBlYCBjYW4gYmUgdXNlZCBpbiB0aGUgY29uZmlndXJhdGlvbiBgVGFibGVDb25maWdgLFxuICAgKiBzbyB0aGF0IHRoZSB0YWJsZSBoZWFkZXJzIGNhbiBiZSBkZWZpbmVkLlxuICAgKi9cbiAgYnVpbGRTdHJ1Y3R1cmUoXG4gICAgdGFibGVUeXBlOiBzdHJpbmcsXG4gICAgZGF0YSQ/OiBPYnNlcnZhYmxlPGFueT5cbiAgKTogT2JzZXJ2YWJsZTxUYWJsZVN0cnVjdHVyZT4ge1xuICAgIGlmICh0aGlzLmhhc1RhYmxlQ29uZmlnKHRhYmxlVHlwZSkpIHtcbiAgICAgIHJldHVybiB0aGlzLmJ1aWxkU3RydWN0dXJlRnJvbUNvbmZpZyh0YWJsZVR5cGUpO1xuICAgIH0gZWxzZSB7XG4gICAgICBpZiAoZGF0YSQpIHtcbiAgICAgICAgcmV0dXJuIHRoaXMuYnVpbGRTdHJ1Y3R1cmVGcm9tRGF0YSh0YWJsZVR5cGUsIGRhdGEkKTtcbiAgICAgIH0gZWxzZSB7XG4gICAgICAgIHJldHVybiB0aGlzLmJ1aWxkUmFuZG9tU3RydWN0dXJlKHRhYmxlVHlwZSk7XG4gICAgICB9XG4gICAgfVxuICB9XG5cbiAgLyoqXG4gICAqIFJldHVybnMgdGhlIHRhYmxlIHN0cnVjdHVyZSBieSBjb25maWd1cmF0aW9uLiBUaGUgY29uZmlndXJhdGlvbiBjYW4gYmVcbiAgICogYnJlYWtwb2ludC1kcml2ZW4sIHdoaWNoIG1lYW5zIHRoYXQgYW4gYWx0ZXJuYXRpdmUgaGVhZGVyIHN0cnVjdHVyZSBjYW5cbiAgICogYmUgY3JlYXRlZCBwZXIgc2NyZWVuIHNpemUuXG4gICAqXG4gICAqIFRoZSBicmVha3BvaW50IGlzIHJlc29sdmVkIGJ5IHRlaCBgQnJlYWtwb2ludFNlcnZpY2VgLlxuICAgKi9cbiAgcHJvdGVjdGVkIGJ1aWxkU3RydWN0dXJlRnJvbUNvbmZpZyh0eXBlOiBzdHJpbmcpOiBPYnNlcnZhYmxlPFRhYmxlU3RydWN0dXJlPiB7XG4gICAgcmV0dXJuIHRoaXMuYnJlYWtwb2ludFNlcnZpY2UuYnJlYWtwb2ludCQucGlwZShcbiAgICAgIG1hcCgoYnJlYWtwb2ludCkgPT4gKHsgLi4udGhpcy5nZXRUYWJsZUNvbmZpZyh0eXBlLCBicmVha3BvaW50KSwgdHlwZSB9KSlcbiAgICApO1xuICB9XG5cbiAgLyoqXG4gICAqIFRoaXMgbWV0aG9kIGdlbmVyYXRlcyBhIHRhYmxlIHN0cnVjdHVyZSBieSB0aGUgaGVscCBvZiB0aGUgZmlyc3QgZGF0YSByb3cuXG4gICAqL1xuICBwcm90ZWN0ZWQgYnVpbGRTdHJ1Y3R1cmVGcm9tRGF0YShcbiAgICB0eXBlOiBzdHJpbmcsXG4gICAgZGF0YSQ6IE9ic2VydmFibGU8YW55PlxuICApOiBPYnNlcnZhYmxlPFRhYmxlU3RydWN0dXJlPiB7XG4gICAgdGhpcy53YXJuKFxuICAgICAgYE5vIHRhYmxlIGNvbmZpZ3VyYXRpb24gZm91bmQgdG8gcmVuZGVyIHRhYmxlIHdpdGggdHlwZSBcIiR7dHlwZX1cIi4gVGhlIHRhYmxlIGhlYWRlciBmb3IgXCIke3R5cGV9XCIgaXMgZ2VuZXJhdGVkIGJ5IHRoZSBoZWxwIG9mIHRoZSBmaXJzdCBkYXRhIGl0ZW1gXG4gICAgKTtcbiAgICByZXR1cm4gZGF0YSQucGlwZShcbiAgICAgIG1hcCgoZGF0YTogYW55W10pID0+IHtcbiAgICAgICAgY29uc3QgaGVhZGVycyA9IE9iamVjdC5rZXlzKGRhdGE/LlswXSkubWFwKChrZXkpID0+ICh7XG4gICAgICAgICAga2V5LFxuICAgICAgICAgIGxhYmVsOiBrZXksXG4gICAgICAgIH0pKTtcbiAgICAgICAgcmV0dXJuIHtcbiAgICAgICAgICB0eXBlOiB0eXBlLFxuICAgICAgICAgIGhlYWRlcnMsXG4gICAgICAgIH0gYXMgVGFibGVTdHJ1Y3R1cmU7XG4gICAgICB9KVxuICAgICk7XG4gIH1cblxuICAvKipcbiAgICogQXMgYSBsYXN0IHJlc29ydCwgdGhlIHRhYmxlIHN0cnVjdHVyZSBpcyByYW5kb21seSBjcmVhdGVkLiBXZSBhZGQgNSB1bmtub3duIGhlYWRlcnNcbiAgICogYW5kIHVzZSB0aGUgYGhpZGVIZWFkZXJgIHRvIGF2b2lkIHRoZSB1bmtub3duIGhlYWRlcnMgdG8gYmUgcmVuZGVyZWQuXG4gICAqL1xuICBwcm90ZWN0ZWQgYnVpbGRSYW5kb21TdHJ1Y3R1cmUodHlwZTogc3RyaW5nKTogT2JzZXJ2YWJsZTxUYWJsZVN0cnVjdHVyZT4ge1xuICAgIHRoaXMud2FybihcbiAgICAgIGBObyBkYXRhIGF2YWlsYWJsZSBmb3IgXCIke3R5cGV9XCIsIGEgcmFuZG9tIHN0cnVjdHVyZSBpcyBnZW5lcmF0ZWQgKHdpdGggaGlkZGVuIHRhYmxlIGhlYWRlcnMpLmBcbiAgICApO1xuXG4gICAgcmV0dXJuIG9mKHtcbiAgICAgIHR5cGUsXG4gICAgICBoZWFkZXJzOiBbXG4gICAgICAgIHsga2V5OiAndW5rbm93bicgfSxcbiAgICAgICAgeyBrZXk6ICd1bmtub3duJyB9LFxuICAgICAgICB7IGtleTogJ3Vua25vd24nIH0sXG4gICAgICAgIHsga2V5OiAndW5rbm93bicgfSxcbiAgICAgICAgeyBrZXk6ICd1bmtub3duJyB9LFxuICAgICAgXSxcbiAgICAgIGhpZGVIZWFkZXI6IHRydWUsXG4gICAgfSk7XG4gIH1cblxuICAvKipcbiAgICogRmluZHMgdGhlIGJlc3QgYXBwbGljYWJsZSB0YWJsZSBjb25maWd1cmF0aW9uIGZvciB0aGUgZ2l2ZW4gdHlwZVxuICAgKiBhbmQgYnJlYWtwb2ludC4gSWYgdGhlcmUgaXMgbm8gY29uZmlndXJhdGlvbiBhdmFpbGFibGUgZm9yIHRoZSBicmVha3BvaW50LFxuICAgKiB0aGUgYmVzdCBtYXRjaCB3aWxsIGJlIHJldHVybmVkLCB1c2luZyBtb2JpbGUgZmlyc3QgYXBwcm9hY2guXG4gICAqXG4gICAqIElmIHRoZXJlIGlzIG5vIG1hdGNoIGZvciBhbnkgYnJlYWtwb2ludCwgdGhlIGZhbGxiYWNrIGlzIGEgY29uZmlndXJhdGlvblxuICAgKiB3aXRob3V0IHRoZSBub3Rpb24gb2YgYSBicmVha3BvaW50LiBPdGhlcndpc2Ugd2UgZmFsbGJhY2sgdG8gdGhlIGZpcnN0XG4gICAqIGF2YWlsYWJsZSBjb25maWcuXG4gICAqL1xuICBwcm90ZWN0ZWQgZ2V0VGFibGVDb25maWcoXG4gICAgdHlwZTogc3RyaW5nLFxuICAgIGJyZWFrcG9pbnQ6IEJSRUFLUE9JTlRcbiAgKTogVGFibGVTdHJ1Y3R1cmVDb25maWd1cmF0aW9uIHtcbiAgICBjb25zdCB0YWJsZUNvbmZpZyA9IHRoaXMuY29uZmlnLnRhYmxlW3R5cGVdO1xuXG4gICAgLy8gZmluZCBhbGwgcmVsZXZhbnQgYnJlYWtwb2ludHNcbiAgICBjb25zdCBjdXJyZW50ID0gdGhpcy5icmVha3BvaW50U2VydmljZS5icmVha3BvaW50cy5pbmRleE9mKGJyZWFrcG9pbnQpO1xuICAgIGNvbnN0IHJlbGV2YW50ID0gdGhpcy5icmVha3BvaW50U2VydmljZS5icmVha3BvaW50c1xuICAgICAgLnNsaWNlKDAsIGN1cnJlbnQgKyAxKVxuICAgICAgLnJldmVyc2UoKTtcblxuICAgIGNvbnN0IGJlc3RNYXRjaDogQlJFQUtQT0lOVCA9IHJlbGV2YW50LmZpbmQoXG4gICAgICAoYnIpID0+ICEhdGFibGVDb25maWcuZmluZCgoc3RydWN0dXJlKSA9PiBzdHJ1Y3R1cmUuYnJlYWtwb2ludCA9PT0gYnIpXG4gICAgKTtcblxuICAgIHJldHVybiBiZXN0TWF0Y2hcbiAgICAgID8gdGFibGVDb25maWcuZmluZCgoY29uZmlnKSA9PiBjb25maWcuYnJlYWtwb2ludCA9PT0gYmVzdE1hdGNoKVxuICAgICAgOiB0YWJsZUNvbmZpZy5maW5kKChzdHJ1Y3R1cmUpID0+ICFzdHJ1Y3R1cmUuYnJlYWtwb2ludCkgfHxcbiAgICAgICAgICB0YWJsZUNvbmZpZ1swXTtcbiAgfVxuXG4gIHByb3RlY3RlZCBoYXNUYWJsZUNvbmZpZyh0YWJsZVR5cGU6IHN0cmluZyk6IGJvb2xlYW4ge1xuICAgIHJldHVybiAhIXRoaXMuY29uZmlnLnRhYmxlPy5bdGFibGVUeXBlXTtcbiAgfVxuXG4gIC8qKlxuICAgKiBQcmludHMgYSBjb252ZW5pZW50IG1lc3NhZ2UgaW4gdGhlIGNvbnNvbGUgdG8gaW5jcmVhc2UgZGV2ZWxvcGVyIGV4cGVyaWVuY2UuXG4gICAqL1xuICBwcml2YXRlIHdhcm4obWVzc2FnZSkge1xuICAgIGlmIChpc0Rldk1vZGUpIHtcbiAgICAgIGNvbnNvbGUud2FybihtZXNzYWdlKTtcbiAgICB9XG4gIH1cbn1cbiJdfQ==